PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?band_id ?name WHERE {
  ?band_id rdf:type	dbo:Genre . 
  ?band_id dbp:name ?name .

} LIMIT 100
